"use client";

import Link from "next/link";
import { ArrowRight, CalendarDays, CheckCircle2, MapPin, Navigation, Plus, Recycle, Sparkles } from "lucide-react";
import { Button } from "@/components/ui/button";
import { WasteDonutChart, WasteTrendChart } from "@/components/dashboard/charts";
import { MetricCard, PageHeader, Panel, StatusBadge } from "@/components/dashboard/primitives";
import type { DashboardRole } from "@/types/dashboard";
import type { DashboardAnalytics, MarketSummary, PickupJob, PickupRequest } from "@/types/mvp";
import { analyticsService } from "@/services/analytics.service";
import { useAsyncResource } from "@/hooks/use-async-resource";

const copy = {
  vendor: { eyebrow: "Fresh Veg Stall 18", title: "Good morning, Anita", description: "Your waste operations are on track. Two pickups are scheduled for today.", action: "Request pickup", href: "/dashboard/vendor/request-pickup" },
  recycler: { eyebrow: "GreenCycle Pvt Ltd", title: "Good morning, Rohan", description: "Seven collections are planned today, with four nearby opportunities available.", action: "Find pickup jobs", href: "/dashboard/recycler/jobs" },
  admin: { eyebrow: "BBMP · Bommanahalli Zone", title: "Operations overview", description: "A live view of collection performance across your markets and recycling network.", action: "Generate report", href: "/dashboard/admin/reports" },
};

export function RoleOverview({ role }: { role: DashboardRole }) {
  const content = copy[role];
  const resource = useAsyncResource(() => analyticsService.getDashboard(role), role);
  return (
    <div className="space-y-6 sm:space-y-8">
      <PageHeader eyebrow={content.eyebrow} title={content.title} description={content.description} action={<Button asChild><Link href={content.href}>{role === "vendor" ? <Plus className="size-4" /> : role === "recycler" ? <Navigation className="size-4" /> : <CalendarDays className="size-4" />}{content.action}</Link></Button>} />
      {resource.loading ? <DashboardLoading /> : resource.error || !resource.data ? <Panel><div className="p-8 text-center"><p className="text-sm font-semibold text-rose-700">Dashboard data is unavailable.</p><button onClick={resource.reload} className="mt-3 text-xs font-semibold text-emerald-600">Try again</button></div></Panel> : <DashboardContent role={role} data={resource.data} />}
    </div>
  );
}

function DashboardContent({ role, data }: { role: DashboardRole; data: DashboardAnalytics }) {
  return <><div className="grid gap-4 sm:grid-cols-2 xl:grid-cols-4">{data.metrics.map((metric, index) => <MetricCard key={metric.label} metric={metric} index={index} />)}</div>{role === "vendor" && <VendorOverview requests={data.recentRequests} />}{role === "recycler" && <RecyclerOverview jobs={data.jobs} />}{role === "admin" && <AdminOverview extraMetrics={data.extraMetrics} markets={data.markets} />}</>;
}

function DashboardLoading() { return <div className="grid gap-4 sm:grid-cols-2 xl:grid-cols-4">{Array.from({ length: 4 }, (_, index) => <div key={index} className="h-32 animate-pulse rounded-2xl border border-slate-200 bg-white dark:border-slate-800 dark:bg-slate-900" />)}</div>; }

function VendorOverview({ requests }: { requests: PickupRequest[] }) {
  return <><div className="grid gap-5 xl:grid-cols-[1.45fr_.55fr]"><Panel title="Recent pickup requests" subtitle="Your latest collection activity" action={<Link href="/dashboard/vendor/requests" className="text-xs font-semibold text-emerald-600">View all</Link>}><div className="overflow-x-auto"><table className="w-full min-w-[700px] text-left"><thead><tr className="border-b border-slate-100 text-[9px] uppercase tracking-wider text-slate-400 dark:border-slate-800">{["Request", "Waste", "Recycler", "Pickup time", "Status"].map(h => <th key={h} className="px-5 py-3 font-semibold sm:px-6">{h}</th>)}</tr></thead><tbody>{requests.slice(0, 3).map(item => <tr key={item.id} className="border-b border-slate-100 last:border-0 dark:border-slate-800"><td className="px-5 py-4 text-xs font-semibold text-slate-800 dark:text-slate-100 sm:px-6">{item.id}</td><td className="px-5 py-4 text-xs text-slate-500 sm:px-6"><span className="font-medium text-slate-700 dark:text-slate-200">{item.waste}</span><br /><span className="text-[10px]">{item.weight}</span></td><td className="px-5 py-4 text-xs text-slate-500 sm:px-6">{item.recycler}</td><td className="px-5 py-4 text-xs text-slate-500 sm:px-6">{item.time}</td><td className="px-5 py-4 sm:px-6"><StatusBadge status={item.status} /></td></tr>)}</tbody></table></div></Panel><Panel title="Recycling score" subtitle="Based on your last 30 days"><div className="px-6 py-7 text-center"><div className="relative mx-auto grid size-40 place-items-center rounded-full border-[12px] border-emerald-100 dark:border-emerald-500/10"><div><p className="text-4xl font-semibold tracking-[-.06em] text-slate-950 dark:text-white">92</p><p className="text-[10px] font-bold uppercase tracking-wider text-emerald-600">Excellent</p></div><div className="absolute -right-2 top-3 grid size-9 place-items-center rounded-xl bg-emerald-600 text-white shadow-lg"><Sparkles className="size-4" /></div></div><p className="mx-auto mt-6 max-w-52 text-xs leading-5 text-slate-500">You segregated 94% of submitted waste correctly this month.</p></div></Panel></div><div className="grid gap-5 xl:grid-cols-[1.45fr_.55fr]"><Panel title="Monthly waste" subtitle="Collected and successfully recycled"><div className="p-4 sm:p-6"><WasteTrendChart /></div></Panel><Panel title="Waste mix" subtitle="By submitted weight"><div className="p-4 sm:p-6"><WasteDonutChart /></div></Panel></div></>;
}

function RecyclerOverview({ jobs }: { jobs: PickupJob[] }) {
  return <><div className="grid gap-5 xl:grid-cols-[1.45fr_.55fr]"><Panel title="Nearby pickup opportunities" subtitle="Matched to your vehicle and material capabilities" action={<Link href="/dashboard/recycler/jobs" className="text-xs font-semibold text-emerald-600">View all jobs</Link>}><div className="grid gap-3 p-4 sm:p-5">{jobs.map(job => <div key={job.id} className="flex flex-col gap-4 rounded-xl border border-slate-100 p-4 transition hover:border-emerald-200 hover:bg-emerald-50/30 dark:border-slate-800 dark:hover:bg-emerald-500/5 sm:flex-row sm:items-center"><span className="grid size-10 shrink-0 place-items-center rounded-xl bg-emerald-50 text-emerald-600 dark:bg-emerald-500/10"><Recycle className="size-[18px]" /></span><div className="min-w-0 flex-1"><div className="flex items-center gap-2"><p className="truncate text-xs font-semibold text-slate-800 dark:text-white">{job.vendor}</p>{job.priority === "High" && <StatusBadge status="High" />}</div><p className="mt-1 flex items-center gap-1 text-[10px] text-slate-400"><MapPin className="size-3" />{job.location}</p></div><div className="flex gap-6 text-xs"><div><p className="text-[9px] uppercase text-slate-400">Material</p><p className="mt-1 font-semibold">{job.waste} · {job.weight}</p></div><div><p className="text-[9px] uppercase text-slate-400">Distance</p><p className="mt-1 font-semibold">{job.distance}</p></div></div><Button asChild size="sm" variant="outline"><Link href={`/dashboard/recycler/jobs?job=${job.id}`}>Review <ArrowRight className="size-3.5" /></Link></Button></div>)}</div></Panel><Panel title="Today's route" subtitle="3 of 7 collections complete"><div className="p-5"><div className="relative space-y-7 before:absolute before:bottom-4 before:left-[15px] before:top-4 before:w-px before:bg-slate-200 dark:before:bg-slate-700">{[{ t: "9:20 AM", n: "Madiwala Flower Market", done: true }, { t: "10:45 AM", n: "Fresh Veg Stall 18", done: true }, { t: "11:30 AM", n: "Lakshmi Flower Mart", done: false }, { t: "1:10 PM", n: "Bommanahalli Market", done: false }].map((stop, i) => <div key={stop.n} className="relative flex gap-3"><span className={`relative z-10 grid size-8 shrink-0 place-items-center rounded-full border-4 border-white dark:border-slate-900 ${stop.done ? "bg-emerald-600 text-white" : i === 2 ? "bg-blue-500 text-white" : "bg-slate-200 text-slate-400 dark:bg-slate-700"}`}>{stop.done ? <CheckCircle2 className="size-3.5" /> : <span className="text-[9px] font-bold">{i + 1}</span>}</span><div><p className="text-[10px] text-slate-400">{stop.t}</p><p className="mt-1 text-xs font-medium">{stop.n}</p></div></div>)}</div></div></Panel></div><Panel title="Collection performance" subtitle="Collected and recovered material over six months"><div className="p-4 sm:p-6"><WasteTrendChart mode="line" /></div></Panel></>;
}

function AdminOverview({ extraMetrics, markets }: { extraMetrics: DashboardAnalytics["extraMetrics"]; markets: MarketSummary[] }) {
  return <><div className="grid gap-3 sm:grid-cols-2 xl:grid-cols-4">{extraMetrics.map(item => <div key={item.label} className="flex items-center gap-3 rounded-xl border border-slate-200 bg-white px-4 py-3.5 dark:border-slate-800 dark:bg-slate-900"><span className="grid size-9 place-items-center rounded-lg bg-slate-100 text-slate-600 dark:bg-slate-800 dark:text-slate-300"><item.icon className="size-4" /></span><div><p className="text-base font-semibold tracking-tight">{item.value}</p><p className="text-[10px] text-slate-400">{item.label}</p></div></div>)}</div><div className="grid gap-5 xl:grid-cols-[1.45fr_.55fr]"><Panel title="Daily collection performance" subtitle="Waste collected and recovered across all active markets"><div className="p-4 sm:p-6"><WasteTrendChart mode="line" /></div></Panel><Panel title="Waste type distribution" subtitle="Today across the zone"><div className="p-4 sm:p-6"><WasteDonutChart /></div></Panel></div><Panel title="Market status" subtitle="Live performance across connected markets" action={<Link href="/dashboard/admin/markets" className="text-xs font-semibold text-emerald-600">View all markets</Link>}><div className="overflow-x-auto"><table className="w-full min-w-[650px] text-left"><thead><tr className="border-b border-slate-100 text-[9px] uppercase tracking-wider text-slate-400 dark:border-slate-800">{["Market", "Requests", "Collected today", "Recycling rate", "Status"].map(h => <th key={h} className="px-6 py-3 font-semibold">{h}</th>)}</tr></thead><tbody>{markets.slice(0, 4).map(item => <tr key={item.market} className="border-b border-slate-100 last:border-0 dark:border-slate-800"><td className="px-6 py-4 text-xs font-semibold">{item.market}</td><td className="px-6 py-4 text-xs text-slate-500">{item.requests}</td><td className="px-6 py-4 text-xs text-slate-500">{item.collected}</td><td className="px-6 py-4"><div className="flex items-center gap-3"><div className="h-1.5 w-20 overflow-hidden rounded-full bg-slate-100 dark:bg-slate-800"><div className="h-full rounded-full bg-emerald-500" style={{ width: item.rate }} /></div><span className="text-xs font-medium">{item.rate}</span></div></td><td className="px-6 py-4"><StatusBadge status={item.status} /></td></tr>)}</tbody></table></div></Panel></>;
}
