import { getSupabaseClient } from "@/services/supabase.client";
import { ServiceError } from "@/services/service-error";
import type { DashboardRole } from "@/types/dashboard";
import type {
  AIAction, AIReport, AIRequest, AIResponseMap, ChatAssistantResult, ChatMessage,
  DashboardAIInsights, DeterministicSmartScore, InventoryAIAnalysis, InventoryAIContext,
  SmartScoreExplanation, WasteImageAnalysis,
} from "@/types/ai";

async function accessToken() {
  const supabase = getSupabaseClient();
  if (!supabase) throw new ServiceError("Supabase is not configured.", 503);
  const { data, error } = await supabase.auth.getSession();
  if (error || !data.session?.access_token) throw new ServiceError("Please sign in to use EcoLoop AI.", 401);
  return data.session.access_token;
}

async function callAI<K extends AIAction>(request: Extract<AIRequest, { action: K }>): Promise<AIResponseMap[K]> {
  const token = await accessToken();
  let lastError = new ServiceError("EcoLoop AI is temporarily unavailable.", 503);
  for (let attempt = 0; attempt < 2; attempt += 1) {
    const controller = new AbortController();
    const timeout = window.setTimeout(() => controller.abort(), 32_000);
    try {
      const response = await fetch("/api/ai", { method: "POST", headers: { Authorization: `Bearer ${token}`, "Content-Type": "application/json" }, body: JSON.stringify(request), signal: controller.signal });
      const body = await response.json() as AIResponseMap[K] & { error?: string };
      if (!response.ok) {
        lastError = new ServiceError(body.error || "EcoLoop AI is temporarily unavailable.", response.status);
        if ((response.status === 429 || response.status >= 500) && attempt === 0) { await new Promise((resolve) => window.setTimeout(resolve, 650)); continue; }
        throw lastError;
      }
      return body;
    } catch (error) {
      lastError = error instanceof ServiceError ? error : new ServiceError(error instanceof Error && error.name === "AbortError" ? "EcoLoop AI took too long to respond. Please try again." : "Network error while contacting EcoLoop AI.", error instanceof Error && error.name === "AbortError" ? 504 : 503);
      if (attempt === 0 && lastError.status !== 401 && lastError.status !== 400) { await new Promise((resolve) => window.setTimeout(resolve, 650)); continue; }
      throw lastError;
    } finally {
      window.clearTimeout(timeout);
    }
  }
  throw lastError;
}

function inventoryFallback(context: InventoryAIContext): InventoryAIAnalysis {
  const overstock = context.inventory.filter((item) => item.stock > item.forecast).map((item) => ({ product: item.name, excess: Math.max(0, item.stock - item.forecast), unit: item.unit, reason: `${item.name} stock exceeds the current demand forecast.` })).sort((a, b) => b.excess - a.excess);
  const savings = context.inventory.reduce((sum, item) => sum + Math.max(0, item.stock - item.forecast) * item.price, 0);
  return {
    summary: overstock.length ? `${overstock.length} product${overstock.length === 1 ? "" : "s"} currently exceed forecast demand.` : "Current inventory is aligned with available forecasts.",
    overstock,
    purchaseRecommendations: overstock.slice(0, 3).map((item) => `Reduce the next ${item.product} purchase by up to ${item.excess} ${item.unit}, then review sales before restocking.`),
    wastePreventionTips: overstock.slice(0, 3).map((item) => `Prioritize ${item.product} for discounting, transfer, or donation before expiry.`),
    estimatedSavings: Math.round(savings),
    priority: overstock.some((item) => item.excess >= 6) ? "High" : overstock.length ? "Medium" : "Low",
    confidence: 0,
  };
}

function scoreFallback(score: DeterministicSmartScore): SmartScoreExplanation {
  const entries = Object.entries(score.metrics).sort((a, b) => b[1] - a[1]);
  const label = (key: string) => key.replace(/([A-Z])/g, " $1").toLowerCase();
  return { ...score, explanation: [`Your strongest measured area is ${label(entries[0][0])} at ${Math.round(entries[0][1])}%.`, `Your score is calculated from five operational metrics, not generated by AI.`], recommendations: [`Focus first on ${label(entries.at(-1)?.[0] ?? "the lowest metric")}, currently ${Math.round(entries.at(-1)?.[1] ?? 0)}%.`] };
}

function fileToDataUrl(file: File) {
  return new Promise<string>((resolve, reject) => {
    const reader = new FileReader();
    reader.onload = () => resolve(String(reader.result));
    reader.onerror = () => reject(new ServiceError("The selected image could not be read.", 400));
    reader.readAsDataURL(file);
  });
}

export const aiService = {
  async analyzeInventory(context: InventoryAIContext): Promise<InventoryAIAnalysis> {
    try { return await callAI({ action: "analyzeInventory", payload: context }); }
    catch (error) { if (error instanceof ServiceError && error.status === 401) throw error; return inventoryFallback(context); }
  },

  async analyzeWasteImage(image: File | string): Promise<WasteImageAnalysis> {
    const imageDataUrl = typeof image === "string" ? image : await fileToDataUrl(image);
    return callAI({ action: "analyzeWasteImage", payload: { imageDataUrl } });
  },

  async generateSmartScore(score: DeterministicSmartScore): Promise<SmartScoreExplanation> {
    try { return await callAI({ action: "generateSmartScore", payload: score }); }
    catch (error) { if (error instanceof ServiceError && error.status === 401) throw error; return scoreFallback(score); }
  },

  async generateRecommendations(role: DashboardRole, context: unknown): Promise<DashboardAIInsights> {
    return callAI({ action: "generateRecommendations", payload: { role, context } });
  },

  async generateWeeklyReport(role: DashboardRole, period: "weekly" | "monthly", context: unknown): Promise<AIReport> {
    return callAI({ action: "generateWeeklyReport", payload: { role, period, context } });
  },

  async chatAssistant(role: DashboardRole, message: string, history: ChatMessage[] = [], context?: unknown): Promise<ChatAssistantResult> {
    try { return await callAI({ action: "chatAssistant", payload: { role, message, history: history.slice(-10), context } }); }
    catch (error) {
      if (error instanceof ServiceError && error.status === 401) throw error;
      return { reply: "EcoLoop AI is temporarily unavailable. Your live inventory, pickup, and analytics data are still available in the dashboard.", suggestedActions: ["Review inventory risks", "Check pickup status"] };
    }
  },
};
